apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: service-registry
  name: service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: service-registry
    spec:
      containers:
        - image: dongnguyen1999/k8s-jenkins:latest
          name: service-registry
          imagePullPolicy: "Always"
          resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: service-registry
  name: service-registry
spec:
  ports:
    - name: 8081-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: service-registry
  type: LoadBalancer
status:
  loadBalancer: {}

