apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: agent
spec:
  containers:
    - name: maven
      image: maven:3.8.7-eclipse-temurin-11
      command:
        - cat
      tty: true
    - name: docker
      image: docker:24.0.7
      command:
        - cat
      tty: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
